/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ForexSignal {
  'id' : bigint,
  'validity' : bigint,
  'direction' : string,
  'pair' : string,
  'reversed' : boolean,
  'strength' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'success' : [] | [boolean],
  'market' : string,
  'exitPrice' : number,
}
export interface ForexStats {
  'total' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'winRate' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'clearHistory' : ActorMethod<[], undefined>,
  'getAllSignals' : ActorMethod<[], Array<ForexSignal>>,
  'getForexCandles' : ActorMethod<[string, string], string>,
  'getForexPrice' : ActorMethod<[string], string>,
  'getNewestSignalId' : ActorMethod<[], bigint>,
  'getOverallStats' : ActorMethod<[], ForexStats>,
  'getStatsByPair' : ActorMethod<[string, string], ForexStats>,
  'saveSignal' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      number,
      [] | [boolean],
      bigint,
      boolean,
    ],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];