/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ForexSignal {
    id: bigint;
    validity: bigint;
    direction: string;
    pair: string;
    reversed: boolean;
    strength: number;
    timestamp: bigint;
    entryPrice: number;
    success?: boolean;
    market: string;
    exitPrice: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ForexStats {
    total: bigint;
    wins: bigint;
    losses: bigint;
    winRate: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    clearHistory(): Promise<void>;
    getAllSignals(): Promise<Array<ForexSignal>>;
    getForexCandles(pair: string, interval: string): Promise<string>;
    getForexPrice(pair: string): Promise<string>;
    getNewestSignalId(): Promise<bigint>;
    getOverallStats(): Promise<ForexStats>;
    getStatsByPair(pair: string, market: string): Promise<ForexStats>;
    saveSignal(pair: string, market: string, direction: string, strength: number, entryPrice: number, exitPrice: number, success: boolean | null, validity: bigint, reversed: boolean): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ForexSignal as _ForexSignal } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async getAllSignals(): Promise<Array<ForexSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForexCandles(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getForexCandles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForexCandles(arg0, arg1);
            return result;
        }
    }
    async getForexPrice(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getForexPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForexPrice(arg0);
            return result;
        }
    }
    async getNewestSignalId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewestSignalId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewestSignalId();
            return result;
        }
    }
    async getOverallStats(): Promise<ForexStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverallStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverallStats();
            return result;
        }
    }
    async getStatsByPair(arg0: string, arg1: string): Promise<ForexStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatsByPair(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatsByPair(arg0, arg1);
            return result;
        }
    }
    async saveSignal(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: boolean | null, arg7: bigint, arg8: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSignal(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSignal(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ForexSignal_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ForexSignal): ForexSignal {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    validity: bigint;
    direction: string;
    pair: string;
    reversed: boolean;
    strength: number;
    timestamp: bigint;
    entryPrice: number;
    success: [] | [boolean];
    market: string;
    exitPrice: number;
}): {
    id: bigint;
    validity: bigint;
    direction: string;
    pair: string;
    reversed: boolean;
    strength: number;
    timestamp: bigint;
    entryPrice: number;
    success?: boolean;
    market: string;
    exitPrice: number;
} {
    return {
        id: value.id,
        validity: value.validity,
        direction: value.direction,
        pair: value.pair,
        reversed: value.reversed,
        strength: value.strength,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        success: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.success)),
        market: value.market,
        exitPrice: value.exitPrice
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ForexSignal>): Array<ForexSignal> {
    return value.map((x)=>from_candid_ForexSignal_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
